### PR TITLE
FM-499: fix audio device switch on Android

### PR DESCRIPTION
**Pull request by cancit**
## Submission Checklist

 - [x] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [x] Tested code changes and observed expected behavior in the example app
 - [x] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Description
[AudioSwitch library requires](https://github.com/twilio/audioswitch?tab=readme-ov-file#activate-a-device) calling `.select` and `.activate` functions to be called in order to switch between audio devices (like speakerphone to earpiece). As far as I see there is no existing way to call activate by using react native functions. I propose modifying `voice_selectAudioDevice` function so that it will immediately activate the device after selecting it. 

## Breakdown

- [Bulleted summary of changes]
- [eg. Updated documentation]
- [eg. Added audio device feature]

## Validation

- Manually tested with app

## Additional Notes

[Any additional comments, notes, or information relevant to reviewers.]

### CODE REVIEW

**Review by mhuynh5757 — APPROVED** [review]
PR looks good to me, thanks @cancit. I'd like to get @afalls-twilio approval first since he's our Android expert.

**Comment by afalls-twilio** [comment]
@cancit What is the usecase for needed to enable output on the device when it is selected while not being on a call?


Activate is called when an incoming call is received and when is Deactivate when a call has ended, such that we are only using the resource when we need it (when on a call).  If you look [here](https://github.com/twilio/audioswitch/blob/d43c7b3bf4b742aa54eb064697364853ca740b68/audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt#L259), Activate is not required to select the audio device.

**Review by afalls-twilio — CHANGES_REQUESTED** [review]
@cancit What is the use-case for needing to enable output on the device when it is selected while not being on a call?


Activate is called when an incoming call is [received](https://github.com/twilio/twilio-voice-react-native/blob/3fd5a6fcd4def5b3afdcd1cfe7f63c57c58f12c0/android/src/main/java/com/twiliovoicereactnative/VoiceService.java#L169) or when an out going call starts [ringing](https://github.com/twilio/twilio-voice-react-native/blob/3fd5a6fcd4def5b3afdcd1cfe7f63c57c58f12c0/android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java#L83)... and is deactivated when a call has [ended](https://github.com/twilio/twilio-voice-react-native/blob/3fd5a6fcd4def5b3afdcd1cfe7f63c57c58f12c0/android/src/main/java/com/twiliovoicereactnative/CallListenerProxy.java#L150), [rejected](https://github.com/twilio/twilio-voice-react-native/blob/3fd5a6fcd4def5b3afdcd1cfe7f63c57c58f12c0/android/src/main/java/com/twiliovoicereactnative/VoiceService.java#L227) or [canceled](https://github.com/twilio/twilio-voice-react-native/blob/3fd5a6fcd4def5b3afdcd1cfe7f63c57c58f12c0/android/src/main/java/com/twiliovoicereactnative/VoiceService.java#L254), such that we are only using the resource when we need it (when on a call).  If you look [here](https://github.com/twilio/audioswitch/blob/d43c7b3bf4b742aa54eb064697364853ca740b68/audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt#L259), Activate is not required to select the audio device and this change would use the resource even when its not needed.

**Comment by cancit** [comment]
thank you @afalls-twilio, we are using a custom accept function and I missed that activate should be called before accepting the call. I added activate call there and now it works 👌

**Pull request closed without merging**
